### ISSUE TITLE
Unable to load market listings.

### ISSUE THREAD

**Issue by voxelgenesis** [Nuklon/Steam-Economy-Enhancer#101]
When I try to load my market page, it forever is stuck on trying to load the list.

In the console, on Chrome, using Tampermonkey, I see: 

![image](https://user-images.githubusercontent.com/2922384/50332956-5a36f700-04c9-11e9-9f12-373205879a20.png)

I'm guessing the failure to load something from that URL is the issue but I don't understand why.

**Comment by Nuklon** [comment]
No idea, looks like TamperMonkey issue, try ViolentMonkey.
