### ISSUE TITLE
Feature request: Ignore minimum priced items when relisting overpriced items

### ISSUE THREAD

**Issue by GillyTheGhillie2** [Nuklon/Steam-Economy-Enhancer#103]
Basically my idea is that any item priced at $0.04/£0.03 etc. should be ignored or checked last when relisting the entire inventory, as they cannot decrease in price further. Alternatively relist overpriced should go in decending price order, as the more expensive an item is, the more likely it is to be overpriced. This would massively speed up relist overpriced on inventories that have lots of cards that sell on the market for minimum price.

**Comment by Nuklon** [comment]
That's not a bad suggestion, feel free to submit a PR to address that.

**Comment by Omicron666** [comment]
@GillyTheGhillie2 Thanks for suggesting this in a successful way hihi

**Comment by woctezuma** [comment]
This is implemented in #122.
