### ISSUE TITLE
Unable to turn The Steam Winter Sale - 2018 Emoticons and Backgrounds into gems

### ISSUE THREAD

**Issue by 1435730** [Nuklon/Steam-Economy-Enhancer#104]
Hi! It returns the message "not turned into gems due to missing gems value".
Thanks for your work!

**Comment by Nuklon** [comment]
Winter Sale is using different method for getting gems value, you can temporarily fix this by removing the get gems value (just hard set it to 100). It's not perfect but given the limited and temporary scope, I'm not that interested in adding a bunch of code for the one week left.

**Comment by aflyhorse** [comment]
Thanks for the workaround.
the badges won't vanish after the event ends. IMHO it is still meaningful to add this snippet in the master.

**Comment by shtrih** [comment]
More neat workaround:
```javascript
    SteamMarket.prototype.getGooValue = function(item, callback) {

        // Prevent requests for WinterSale2018 items, hard code the value to 100
        var itemName = item.name || item.description.name;
        if (itemName.includes(":cozy") || itemName.includes("Cozy Cottage")) {
            return callback(ERROR_SUCCESS, {goo_value: 100});
        }

        try {
            // ...
```
