### ISSUE TITLE
Option to show more inventory items on one page

### ISSUE THREAD

**Issue by 07416** [Nuklon/Steam-Economy-Enhancer#106]
Steam only displays 25 items on a inventory page, more desktop-friendly amount would be 50 or hundred. Always showing all inventory items on one page can be optimal, but will be slow on large inventories.

![687474703a2f2f692e696d6775722e636f6d2f3942754c4e37382e706e67](https://user-images.githubusercontent.com/14923168/50563317-7ede6a80-0d24-11e9-8cf7-ccdacc386cf7.png)

**Comment by 07416** [comment]
Steam only displays 25 items on a inventory page, more desktop-friendly amount would be 50 or hundred. Always showing all inventory items on one page can be optimal, but will be slow on large inventories.

**Comment by Nuklon** [comment]
The inventory is already quite buggy so I'm not looking to add this. A smaller window size is a nice workaround.
