### ISSUE TITLE
Doesn't work with Tampermonkey on Firefox

### ISSUE THREAD

**Issue by Sh4l1k4** [Nuklon/Steam-Economy-Enhancer#118]
Doesn't work with Tampermonkey on Firefox
Works with Tampermonkey on Chrome
Works with Greasemonkey on Firefox

**Comment by woctezuma** [comment]
It works with Violentmonkey on Firefox.

**Comment by Nuklon** [comment]
Closing as Tampermonkey on Firefox is a mess last time I've tried it, Violentmonkey is the way to go.
