### ISSUE TITLE
First item bypass confirmation

### ISSUE THREAD

**Issue by Teezton** [Nuklon/Steam-Economy-Enhancer#119]
Hi, 
Everytime I press **Sell All Items** the first item bypass the confirmation.

For example, today I got 2 items, pressed **Sell All Items** and I just got 1 Item to confirm. Went to **My Market History** to find the item already sold without my confirmation to sell.

![image 003](https://user-images.githubusercontent.com/5905860/53346068-2edbe880-390e-11e9-9ecb-ec5ebcd5e804.png)

It's _Steam Economy Enhancer_ fault or _Steam_? Another problem.. I don't get notification on Steam (Android) of items to confirm when I press **Sell All Items**.

**Comment by Bonsai99** [comment]
Normal behavior
https://steamcommunity.com/groups/community_market#announcements/detail/1705067494681435160
