### ISSUE TITLE
Sell selected Items - strange limitation behavior

### ISSUE THREAD

**Issue by Whisperstorm** [Nuklon/Steam-Economy-Enhancer#12]
Thanks for updating the script! Unfortunately ive encountered a strange limitation in the "sell selected items" function. It stops working exactly when the item (cards in my case) no 1815 was reached. All following cards can be selected but if you try to sell them, it goes into the infinite "selling items" animation.  When trying to sell only the 25 items on the inventory page 73, only the first 15 are being sold and the rest is not detected as all of the following cards. So basically all cards beyond inventory page 73 cant be sold. 

Im also getting performance issues after selecting an item when any particular game filter was applied in the inventory. Its gone as soon as the game filter is deactivated.

Im using newest Chrome with Tampermonkey

**Comment by Nuklon** [comment]
That's really strange, I don't have 73 pages of items in inventory to try out though (even if I delist all items I have).

Can you give an example about the performance issues (how to reproduce)?

**Comment by Whisperstorm** [comment]
Show advanced filters in the steam inventory ->select any game filter and click on any filtered item. The browser tab stops responding for about 2-3 seconds. At least for me. Maybe its a local issue. 

Ive also tried to sell items  without activating the "marketable" filter. It stops exatcly when the last working marketable item is reached, which would be on page 73 when the "marketable" filter is active. I suppose that the marketable item ids start to change approximatly when the item 1800 is reached or something like that :D

**Comment by Nuklon** [comment]
I don't have any lag with using the advanced filters. 

I don't have 73+ inventory pages so if you want this fixed you'll need to send me a tradeoffer for ~2000 items or try to fix it yourself, sorry!
