### ISSUE TITLE
NaN price for inventory item

### ISSUE THREAD

**Issue by Revadike** [Nuklon/Steam-Economy-Enhancer#121]
![image](https://user-images.githubusercontent.com/4411977/54870986-eb11bd00-4dad-11e9-8962-60860e76384b.png)

Item: https://steamcommunity.com/market/listings/753/338050-Anoxemia%20background%20(Profile%20Background)-26
My inventory: https://steamcommunity.com/id/revadike/inventory/#753

It works fine for other inventory items

**Comment by TheOddball** [comment]
Doesn't happen for me. Might be a currency thing.

**Comment by Revadike** [comment]
> Doesn't happen for me. Might be a currency thing. I use USD.

Nope, it's item specific. The one I linked.

**Comment by Nuklon** [comment]
Probably Valve glitch, I've tested in USD and EUR and they both have prices.

**Comment by Revadike** [comment]
Yes, it is working now. You may want to improve error handling though, instead of displaying NaN.
