### ISSUE TITLE
feature request: Treat equal prices of items as overpriced

### ISSUE THREAD

**Issue by pacopepepipo** [Nuklon/Steam-Economy-Enhancer#124]
Recently I've been learning why some items are not sold by me when I was the first one to put that price, just to see later that one item was sold at the same price I  put and was not mine.

Some people from countries with other currencies, can put decimals on the price of what It's already a decimal on my currency

For example, I can sell for 0.15 or 0.14 but them with their currencies, can sell the equivalent to 0.141 0.142 0.143, etc, making for some countries that item the lowest price, not mine, while I see both of them at the same price.

Could be possible to treat or mark the items that have more of the same on the market at the same price as an overpriced one, so I can auto select them to put again at a lower price?

cheers

**Comment by Nuklon** [comment]
The problem with that is that you're going to go to a bottom, they will price lower and lower and lower. In USD/EUR the minimum is 0,03 cents, but in RUB/ARS for example they can sell an item worth 0,005 cents USD/EUR, you can never compete with that.

**Comment by Nuklon** [comment]
To add to that, you can add -0,01 to calculated value in options to get this behavior.
