### ISSUE TITLE
Default values for the minimum price are too high

### ISSUE THREAD

**Issue by woctezuma** [Nuklon/Steam-Economy-Enhancer#126]
![change the default values](https://i.imgur.com/Gr4Vwcj.png)

I have changed the values for the minimum price, because the default values are too high:
- normal cards listed for 0.05€,
- foil cards for 0.15€,
- and other items for 0.05€.

However, it is now common to find:
- normal cards listed for 0.03€,
- foil cards for 0.04€,
- and other items for 0.03€.

This means that the default values lead to a lot of useless listings, which are likely never going to be sold.

For instance:

![normal card](https://i.imgur.com/je2uJ2m.png)
![foil card](https://i.imgur.com/ynCJQeP.png)
![other items](https://i.imgur.com/gWwxVIK.png)

**Comment by friskyplatypus** [comment]
This isn't an issue... A lot of people don't want to sell their items for the minimum price. The default values are fine, there are only a few games where the quantities available mean thousands of items listed at .03

**Comment by TheOddball** [comment]
@woctezuma @Nuklon This is a bug relating to currencies. Those values remain the same no matter the currency, those are normal values for USD. Closable.

**Comment by woctezuma** [comment]
@friskyplatypus 

Nobody is forcing anyone to sell the items for the minimum price. You always sell at the optimal price, which is automatically computed by the add-on according to your criterion. The thing is that for **many** games (not "only a few games" as you seem to believe), the optimal price is Steam Market's minimal price. The arbitrary threshold leads to sub-optimal prices, which means the items will never be sold. What is the point of listing an item for sale if the sale never happens in your lifetime?

![Criteria](https://i.imgur.com/JQtW3nm.png)

@TheOddball 

I don't understand how this could be a bug for "foil" cards (minimum is arbitrarily set to $0.15, but it could be set to $0.05 as the other two).

**Comment by woctezuma** [comment]
Anyway, my main issue was with the maximum as described in #127. If people do not realize that they ask for too little money to sell their items, then they do not earn as much money as they could from the sale.

To the contrary, if people ask too much money to sell their items, as I described here in #126, then the sale will never happen, the listing is dummy, but at least nothing is lost. Feel free to close the issue if you will.

**Comment by Nuklon** [comment]
The default prices are totally fine if you're selling the first item(s). I've sold a lot of cards near default prices. They're not too high but also not too low so you can still get some money. If there are lower prices on the market then these prices will obviously not be used. Otherwise, you're free to change the prices in the settings, they're remembered after all 👍
