### ISSUE TITLE
Default value for the maximum price of other items is too low

### ISSUE THREAD

**Issue by woctezuma** [Nuklon/Steam-Economy-Enhancer#127]
![change the default values](https://i.imgur.com/Gr4Vwcj.png)

I have changed the value for the maximum price of other items, because the default value is too low:

- other items for 10€.

However, it is now common to find other items listed for a lot more than that.

This means that the default value may lead to a loss of a lot of money for some people, after a mis-click makes them sell their worthy items for 10€, without any warning.

![dragonclaw hook](https://i.imgur.com/J8yGzX2.png)

**Comment by Nuklon** [comment]
SEE is not meant to automate selling items worth over 600€. For these cases you'd be better off setting your own price (either in settings or sell manually). Furthermore, buy offers are always respected regardless of maximum price, so if someone offers 650€ for an item it will place a sell order for that instead.
