### ISSUE TITLE
Trying to sell unmarketable items

### ISSUE THREAD

**Issue by Omicron666** [Nuklon/Steam-Economy-Enhancer#13]
It wasn't trying to sell unmarketable cards, in previous versions.

**Comment by Nuklon** [comment]
Nothing changed in that regard (it still checks if it's marketable). 

Can you send me a [tradeoffer](https://steamcommunity.com/tradeoffer/new/?partner=94613954&token=6OR2RY2I) of one of these unmarketable cards so I can try it out myself (as I don't have any)?

**Comment by Omicron666** [comment]
Sure. :-)
If you don't get one before, I will send you one in 19 hours and 30 minutes :P (account unable to trade till then)

**Comment by Nuklon** [comment]
Alright, I don't think I will, so I'll await it, thanks :)

**Comment by Omicron666** [comment]
Trade sent.
It will try to sell the unmarketable item when Sell all card button is used.
No buy offer for the wallpaper item. Selling it will use the max price instead of normal price.

**Comment by Nuklon** [comment]
Thanks, I received them and I'll check it out soon (with a bit of luck tomorrow).

**Comment by Nuklon** [comment]
The selling of cards that aren't marketable should be fixed.

The wallpaper only seems to happen on Chrome, it works in Firefox. I'll investigate that some more.

**Comment by Nuklon** [comment]
Also fixed the wallpaper issue. This also happened on Firefox with the default price values.
Will update the script later after I'm looking into the other issues.
