### ISSUE TITLE
Massive problem with listing items for the lowest market price

### ISSUE THREAD

**Issue by KantVoors** [Nuklon/Steam-Economy-Enhancer#136]
I've noticed about a year ago when I used this script that a lot of my items were being set on the market for higher prices than they should be. As an example, a lot of trading cards and backgrounds that are worth 0.03$, meaning you get 0.01$, were being sold at 0.05$ instead. I didn't bother with it then because there were just too many of them to relist all of them, and there isn't an option to manually pick a price. Now I've installed the script again and I see that it doesn't recognize overpriced items. Certain things that are sold at 0.03$ are still at 0.05$, and it seems to notice that on the market list, yet doesn't consider them "overpriced" and they're still green.

**Comment by KantVoors** [comment]
Here's an example
01 / 70 - Relentless Zombie retrying listing because you cannot sell any items until your previous action completes.
01 / 70 - Relentless Zombie listed for 0.05€, you will receive 0.03€.
02 / 70 - Untested Grunt listed for 0.05€, you will receive 0.03€.
03 / 70 - Untested Grunt listed for 0.05€, you will receive 0.03€.
04 / 70 - Trebuchets listed for 0.05€, you will receive 0.03€.
05 / 70 - Iron Fog Goldmine listed for 0.05€, you will receive 0.03€.
06 / 70 - Bronze Legionnaire listed for 0.05€, you will receive 0.03€.
07 / 70 - Bronze Legionnaire listed for 0.05€, you will receive 0.03€.
08 / 70 - Avernus' Blessing listed for 0.05€, you will receive 0.03€.
09 / 70 - Avernus' Blessing listed for 0.05€, you will receive 0.03€.
10 / 70 - Sucker Punch listed for 0.05€, you will receive 0.03€.
11 / 70 - Grazing Shot listed for 0.05€, you will receive 0.03€.
12 / 70 - Assassin's Apprentice listed for 0.05€, you will receive 0.03€.
13 / 70 - Poised to Strike listed for 0.05€, you will receive 0.03€.
14 / 70 - Poised to Strike listed for 0.05€, you will receive 0.03€.
15 / 70 - Tower Barrage listed for 0.05€, you will receive 0.03€.
16 / 70 - Foresight listed for 0.05€, you will receive 0.03€.
17 / 70 - Foresight listed for 0.05€, you will receive 0.03€.
18 / 70 - Pick a Fight listed for 0.05€, you will receive 0.03€.
19 / 70 - Vhoul Martyr listed for 0.05€, you will receive 0.03€.
20 / 70 - Vhoul Martyr listed for 0.05€, you will receive 0.03€.
21 / 70 - Cunning Plan listed for 0.05€, you will receive 0.03€.
22 / 70 - Combat Training listed for 0.05€, you will receive 0.03€.
23 / 70 - Strafing Run listed for 0.05€, you will receive 0.03€.
24 / 70 - Strafing Run listed for 0.05€, you will receive 0.03€.
25 / 70 - Strafing Run listed for 0.05€, you will receive 0.03€.
26 / 70 - Juke listed for 0.05€, you will receive 0.03€.
27 / 70 - Payday listed for 0.05€, you will receive 0.03€.
28 / 70 - Buying Time listed for 0.05€, you will receive 0.03€.
29 / 70 - Rumusque Blessing listed for 0.05€, you will receive 0.03€.
30 / 70 - Arcane Censure listed for 0.05€, you will receive 0.03€.
31 / 70 - Arcane Censure listed for 0.05€, you will receive 0.03€.
32 / 70 - Disciple of Nevermore listed for 0.05€, you will receive 0.03€.
33 / 70 - Bellow listed for 0.05€, you will receive 0.03€.
34 / 70 - Ogre Magi listed for 0.05€, you will receive 0.03€.
35 / 70 - Sven listed for 0.05€, you will receive 0.03€.
36 / 70 - Rebel Instigator listed for 0.05€, you will receive 0.03€.
37 / 70 - Self Sabotage listed for 0.05€, you will receive 0.03€.
38 / 70 - Burning Oil listed for 0.05€, you will receive 0.03€.
39 / 70 - Howling Mind listed for 0.05€, you will receive 0.03€.
40 / 70 - ...And One For Me listed for 0.05€, you will receive 0.03€.
41 / 70 - Bristleback listed for 0.05€, you will receive 0.03€.
42 / 70 - Bristleback listed for 0.05€, you will receive 0.03€.
43 / 70 - Treant Protector listed for 0.05€, you will receive 0.03€.
44 / 70 - Claymore listed for 0.05€, you will receive 0.03€.
45 / 70 - Hero's Cape listed for 0.05€, you will receive 0.03€.
However if you check the price, it's clearly going for 0.03€ on the Steam market, not 0.05€, so what is causing this?

**Comment by KantVoors** [comment]
Pressing relist doesn't do anything to the items either

**Comment by kraivux** [comment]
In the settings there is a minimum and maximum for items, 0.05 is the default so I'm assuming that's what you need to change.

**Comment by KantVoors** [comment]
do you know why this was implemented in the first place, or why the default is not 0.03, like the actual minimum for dollars and euros?

**Comment by KantVoors** [comment]
I just don't see why the minimum can't be whatever the minimum price on an item currently is but I'm closing this issue because there is a solution
