### ISSUE TITLE
mass deleting buy orders on market page not working

### ISSUE THREAD

**Issue by pacopepepipo** [Nuklon/Steam-Economy-Enhancer#137]
when you try to check all and then delete all buy orders, it doesn't work

1- click select all
2- click remove selected
3- all items go in red
4- all the items stay there and are not deleted.

**Comment by woctezuma** [comment]
I can confirm the issue is still there.

Related:
- #76

Maybe related:
- #14

**Comment by woctezuma** [comment]
I see this error message after the main page for Steam Market has been loadeds.

![Picture](https://i.ibb.co/qxZt6J6/2022-04-01-19-06-13.png)

**Comment by woctezuma** [comment]
This is the error which happens when I select a buy order and try to "remove selected" buy orders.

![Picture](https://i.ibb.co/FX0Fbyz/2022-04-01-19-07-52.png)

**Comment by woctezuma** [comment]
I ended up using https://github.com/bukson/steampy#market-methods

**Comment by disanyixing** [comment]
SteamMarket.prototype.removeListing = function (item, callback /*err, data*/) {
        var sessionId = readCookie('sessionid');
            $.ajax({
                type: "POST",
                url: window.location.protocol + '//steamcommunity.com/market/removelisting/' + item,
                data: {
                    sessionid: sessionId
                },
                success: function (data) {
                    callback(ERROR_SUCCESS, data);
                },
                error: function () {
                    // return callback(ERROR_FAILED);
                    $.ajax({
                        type: "POST",
                        url: window.location.protocol + '//steamcommunity.com/market/cancelbuyorder/',
                        data: {
                            sessionid: sessionId,
                            buy_orderid: item
                        },
                        success: function (data) {
                            callback(ERROR_SUCCESS, data);
                        },
                        error: function () {
                            return callback(ERROR_FAILED);
                        },
                        crossDomain: true,
                        xhrFields: {
                            withCredentials: true
                        },
                        dataType: 'json'
                    });
                },
                crossDomain: true,
                xhrFields: {
                    withCredentials: true
                },
                dataType: 'json'
            });
    };
![image](https://github.com/Nuklon/Steam-Economy-Enhancer/assets/72839560/d8971555-f37e-4920-915d-fd164aa6d3ae)
