### ISSUE TITLE
Pay you a coffee

### ISSUE THREAD

**Issue by Kerooker** [Nuklon/Steam-Economy-Enhancer#138]
This extension helps me a lot with steam trading.

I'll happily pay you a coffee for it, if you provide a link for donations of any sort.

**Comment by Nuklon** [comment]
Feel free to send something to https://steamcommunity.com/id/nuklon/. I don't have any other funding links at the moment (hopefully GitHub Sponsors will open up soon for everyone).

**Comment by TheOddball** [comment]
@Nuklon this is closable.
