### ISSUE TITLE
[Possible bug] Having buying orders makes script to stop working properly.

### ISSUE THREAD

**Issue by Tomasety-III** [Nuklon/Steam-Economy-Enhancer#14]
This comes from my closed issue https://github.com/Nuklon/Steam-Economy-Enhancer/issues/11 

I will try to explain once more. 

Having buying orders at the same time as selling items listed on market can break script functionality.

It happens at least when the following requisite is met.

If a buying order has its first string with a higher sorting priority than the first string's item listed on market then script stops to work properly.

For example. 

https://i.imgur.com/UaAcaID.png
The first item on my selling listing table (I don't know why script mixes buying orders and selling orders on the same table) is a buying order whose first string is a number 2. 
Second item is a selling order listed whose first string is a a colon => ":"

Since a number goes first before a letter and a symbol in an ascendant alphabetic sorting then the first buying order has top priority on my selling listing. That's the cause which makes script to stop working as you can see on the picture. ( No green price section is highlighted)

But if I remove that first buying order (you can see on the next picture: https://i.imgur.com/GLmBU7g.png) then I can see how script works till it finds next buying order on my selling items list and in that case stops to working once again 

Thanks once again @Nuklon

**Comment by Phyxion** [comment]
Ah, alright, I think I get it now, I'll investigate.

**Comment by Nuklon** [comment]
Ah, alright, I think I get it now, I'll investigate.

**Comment by Nuklon** [comment]
I can confirm this is broken indeed, I'll see if I can fix this one too.

**Comment by Nuklon** [comment]
Also fixed.
