### ISSUE TITLE
Is it possible to make this script compatible with Greasemonkey?

### ISSUE THREAD

**Issue by Ryzhehvost** [Nuklon/Steam-Economy-Enhancer#141]
First of all, I want to thank you for this extremely useful script, it saved me many hours of my life.
I wanted to ask if there is a way to support Greasemonkey. Sometimes I have to work on pretty old PCs, Chrome and new Firefox are way to slow there, so I switched to Palemoon. It's a nice browser, but it does not support WebExtensions, and hence, there is no Tampermonkey (or Violentmonkey) addon for it, only Greasemonkey. And on Greasemonkey your script are mostly inoperable - it adds buttons to inventory page, but that's it - none of them work, not even an options one. It seems there are some differences in unsafeWindow implementation between Greasemonkey and Tampermonkey.
I will be very grateful if you could consider possibility of making your script compatible with Greasemonkey

**Comment by zdat** [comment]
I'm interested in this too. Greasemonkey is my choice for user scripts so I'd love if it was supported.

**Comment by guoliang** [comment]
what makes it not working with greasemonkey? I thought all these kind of script works with greasemonkey and its spawns?

**Comment by Ryzhehvost** [comment]
@guoliang if I knew what exactly prevents it from working - I would have fixed it myself.

**Comment by Nuklon** [comment]
Greasemonkey is a mess after their last updates, but if someone is interested in fixing this then please submit a pull request for it.
