### ISSUE TITLE
Steam prices loading very slowly

### ISSUE THREAD

**Issue by nawias123** [Nuklon/Steam-Economy-Enhancer#145]
Is it possible to speed up loading prices on trade offers and inventories? Or to make them load all by one time not just one by one. Mayebe it's simple code change that i don't know cause i'm bad at programming :(

Greettings

**Comment by GaugeK** [comment]
Yeah, it takes like 3 seconds to load the prices for *one* item.

Is it not possible to make it try get the prices for like 5 at once?

**Comment by Nuklon** [comment]
It's possible, but you will be blocked by Steam due to too many requests. The current speed is carefully chosen to avoid that from happening. Best to just open the page and wait for a bit, or do not have such large inventories.
