### ISSUE TITLE
Broken script on market item page.

### ISSUE THREAD

**Issue by Omicron666** [Nuklon/Steam-Economy-Enhancer#15]
Broken script :
http://i.imgur.com/BTUM8qO.png
The script won't auto-resell items on item page. http://steamcommunity.com/market/listings/753/313650-Family%20meeting

**Comment by Nuklon** [comment]
It's because there's no list of listings created for item pages. I'll see if I can fix this or I might remove the auto relist feature on the item page.

**Comment by Nuklon** [comment]
Also fixed.
