### ISSUE TITLE
Stuck at "Loading market listings"

### ISSUE THREAD

**Issue by shigutso** [Nuklon/Steam-Economy-Enhancer#150]
I have 10 items listed and the message "Loading market listings" never stops.
Any clue?
Using tampermonkey on Chrome

**Comment by FrancoCJ** [comment]
Same

**Comment by friskyplatypus** [comment]
This started for me with the newest release. I have verified that it is an issue with this script as it loads just fine when the script isn't enabled.

**Comment by Nuklon** [comment]
Use violentmonkey.
