### ISSUE TITLE
Sell All Items / Sell All Cards not working

### ISSUE THREAD

**Issue by Merudo** [Nuklon/Steam-Economy-Enhancer#161]
When I click "Sell All Items" or the "Sell All Cards" button, I see a message telling me the cards & items are getting listed, and the money for each.

However nothing actually gets listed, if I refresh or access my steam client, all the cards are untouched and not in the market.

**Comment by naqaden** [comment]
Did the confirmations appear in your Steam app?

**Comment by Merudo** [comment]
Oh yeah it did! My bad I though I could confirm from the website & pc client.
