### ISSUE TITLE
Can make a game that automatically buys cards with swappable cards?    可以做一个自动购买带集换式卡牌的游戏吗？

### ISSUE THREAD

**Issue by LSDGQ** [Nuklon/Steam-Economy-Enhancer#164]
Can make a plugin that automatically buys swappable cards? Just go buy a very low-priced game and then this game comes with a higher value of swappable cards than the game, such a plug-in. I wish there could be such a plugin that I would like to spend 50 rmb. Thank you, forget it if it doesn't work
请问，可以做一个自动购买集换式卡牌的插件吗？ 就去购买价格很低的游戏然后这个游戏所带的集换式卡牌价值比游戏高,这样的插件。我希望可以有这样的插件 我愿意花50人民币。谢谢你 如果不行就算了

**Comment by woctezuma** [comment]
I think a game can only be cheaper than its droppable trading cards in very few locations, and I doubt China is one of them.

**Comment by LSDGQ** [comment]
> 从理论上讲，一款游戏可能比其可掉落的交易卡的总和便宜。实际上，这只在**极少数地方**是正确的，我怀疑中国是其中之一。您最终会发现一些在阿根廷或土耳其售价 0.09 欧元的游戏，并希望以每张 0.05 欧元的价格出售其 ~3 张集换式卡（扣除 Steam 市场费用后为 0.03 欧元）。**不值得开发时间。**
> 
> 购买所有游戏会更简单、更省时：
> 
> * 最高价值0.09欧元，
> * 并支持集换式卡牌，
> 
> **希望**您通过出售卡片免费获得一些游戏，并完成任务。

I've gotten 600 cards so far, and 20 of them are valuable because of the region, and my Steam account is located in Argentina, so it's cheap after all   Probably because I prefer free stuff
