### ISSUE TITLE
Request: Add and option to list items to meet the highest buy order, if one exists

### ISSUE THREAD

**Issue by leftbones** [Nuklon/Steam-Economy-Enhancer#167]
Example: I have a Professional Bushwacka Kit (Team Fortress 2) that Steam Economy Enhancer lists at $6.91, because the lowest listed one is $6.96 -- This is fine, except there are 20+ buy orders for $4.56 or lower. In some cases like this, I'd rather just take the slightly lower price just to get rid of the items.

**Comment by woctezuma** [comment]
The problem is you will get rate-limited if you try that, because you won't use the same endpoint to find the prices.

**Comment by leftbones** [comment]
> The problem is you will get rate-limited if you try that, because you won't use the same endpoint to find the prices.

Bummer, so theoretically there's no way around that?

**Comment by woctezuma** [comment]
With more lenient rate-limits, this would be doable. You would make requests with [`GET /market/itemordershistogram`](https://github.com/Revadike/InternalSteamWebAPI/wiki/Get-Market-Item-Orders-Histogram) to fetch the bid, i.e. the highest buy order. However, there has been a recent issue (#165) with rate-limits to this end-point.

**Comment by woctezuma** [comment]
True. 😅 

https://github.com/Nuklon/Steam-Economy-Enhancer/blob/c27db660a2e5494b02bacdef63c245b885191d2d/code.user.js#L336-L342

**Comment by leftbones** [comment]
> 

I realize now I worded my initial post wrong, I meant to ask about this feature for the “Sell All” buttons. I have like a hundred cards, listing them all individually is doable but annoying. 

When I use the “Sell All” button currently, it appears to list them at the price that undercuts the lowest sell order, rather than matching the highest buy order.

**Comment by woctezuma** [comment]
> When I use the “Sell All” button currently, it appears to list them at the price that undercuts the lowest sell order

This is cutomizable.

![Settings](https://i.imgur.com/3E1YTOT.png)

**Comment by Nuklon** [comment]
Yes, this is already implemented 🙂
