### ISSUE TITLE
Item "not turned into gems due to unknown error."

### ISSUE THREAD

**Issue by woctezuma** [Nuklon/Steam-Economy-Enhancer#169]
Since yesterday, I get an error when trying to turn any item into gems with your script.
I see there is a call to `ajaxgrindintogoo` which returns a `403 Forbidden` error.

> [Item] not turned into gems due to unknown error.

![Button](https://i.imgur.com/aTqKqx6.png)

However, turning items into gems works fine when using the button placed on each item by Steam, which contacts:
- `/id/MY_ID/ajaxgrindintogoo`

rather than:
- `/my/ajaxgrindintogoo`.

![Steam button](https://i.imgur.com/jZxhobW.png)

**Comment by woctezuma** [comment]
I can get the script working if I change this line:

https://github.com/Nuklon/Steam-Economy-Enhancer/blob/93a6be34deac4f5b857be082391721f81eb9321b/code.user.js#L80

to:

**Comment by rts7** [comment]
Same thing happens for unpacking booster packs. The steam button works but the script's button doesn't and it is not fixed by the solution. Unfortunately I don't know how to see what steam's button contacts.
