### ISSUE TITLE
Move the new options button

### ISSUE THREAD

**Issue by Royalgamer06** [Nuklon/Steam-Economy-Enhancer#17]
It took me a good few minutes to find the new options button. The new location isn't obvious at all, imo. I suggest you do something like this instead:
![](https://i.imgur.com/waDPv5E.png)

Just my cup of tea. 👍

**Comment by Nuklon** [comment]
I'll keep it at the top for these reasons:
- It's where the other settings from Steam are also.
- Once you know where it is you can easily find it.
- It's the same place for both inventory and market page.

That said, I'll add a description to the readme where to find the options button.
