### ISSUE TITLE
Sell 0.01$ less than the lowest price

### ISSUE THREAD

**Issue by hynxx** [Nuklon/Steam-Economy-Enhancer#172]
Help me make each lot sell $0.01 less than the lowest price. It seems that this functionality has already been done, and, apparently, I'm doing something wrong. [Click to view my settings](https://prnt.sc/iB9LtRaHOJ5W). Sale is at the lowest price at the moment.

I need this for a quick sale of non-popular lots with a large amount.

**Comment by naqaden** [comment]
Try changing the top setting:
Calculate prices as the: `Lowest sell listing`

**Comment by woctezuma** [comment]
Also, change the minimal price if needed.
