### ISSUE TITLE
"Too much requests"

### ISSUE THREAD

**Issue by cicciocc** [Nuklon/Steam-Economy-Enhancer#177]
Steam leaves me with the "too much requests" message, and block me (my IP) for hours sometimes, but mostly, very often, when I use and keep your script active.

Last year Valve reduced the number of requests/per hour (per user) and blame this on various plugins and third parties, as yours, because these make too much continuos and frequent xhr requests.

Just saying...I suffer from both: not having enough infos via plain steam/not having Economy Enhancer active. 
Either way I am slowed down in either uses

To be more specific: I think it is caused when opening users inventories (already big junks of unuseful data) during trades, and S.E.E. also add downloads for every single price for every item on it.

**Comment by woctezuma** [comment]
Related:
- #165 
- #168
