### ISSUE TITLE
Not Working // Automatically relist overpriced market listings (slow on large inventories)

### ISSUE THREAD

**Issue by darkdroider** [Nuklon/Steam-Economy-Enhancer#180]
Automatically relist overpriced market listings (slow on large inventories):  function not working

Script removes the overpriced cards, but dont sell again.
I don't know if it was some recent change, or a problem related to Steam/Valve itself

**Comment by MonthOLDpickle** [comment]
Same thing is happening. It only removes the card. Even the relist selected does as well.

**Comment by Nuklon** [comment]
Fixed in latest commit, will release update soon.

**Comment by darkdroider** [comment]
my hero <3
