### ISSUE TITLE
Relist doesn't relist, just removes.

### ISSUE THREAD

**Issue by MonthOLDpickle** [Nuklon/Steam-Economy-Enhancer#181]
W10 64 bit pro on Vivaldi and other browsers.

Basically even with the updating on 7/5 (going off memory)...relist doesn't work. It just removes.

Is this a bug or did steam change something so it doesn't work anymore?

**Comment by woctezuma** [comment]
- #180

**Comment by Nuklon** [comment]
Fixed in latest commit, will release update soon.
