### ISSUE TITLE
Showing of the lowest listed price for items in inventory and trade offers.

### ISSUE THREAD

**Issue by Botan626** [Nuklon/Steam-Economy-Enhancer#19]
Hello, Nuklon.

Could you, please, add an option to turn this feature on and off, as it seems to slow down the perfomance of actions highly when having a big inventory.

**Comment by Nuklon** [comment]
How many items are we talking about? I've no issues with it with 50 pages of items.

**Comment by Botan626** [comment]
135 pages, but had freezes with lower amount of pages.

Doing a simple task like moving 90 items from single game to bot account causes this problem, for instance. When starting typing in the search field for a specific item, it all just halts.

Turning script off solves the issue. Using SIH for the option to select all items on page causes no problems.

But I really want to use this script only for the relisting option.

**Comment by Botan626** [comment]
It literally takes 25 seconds to load card info for selling after the search for specific game was taken in the inventory.

**Comment by Nuklon** [comment]
Please checkout the latest commit, it should perform much better with large inventories. 

The loading of the prices is all done async (was already like that) and should not cause any additional lag. What was laggy was observing the children in the trade offer window, I've now reduced this to a much smaller part of the window and everything now loads almost immediately.

**Comment by Botan626** [comment]
Same, no changes.

What data I can provide you to help with this?

**Comment by Nuklon** [comment]
Step by step to reproduce might help.
________________________________

**Comment by Botan626** [comment]
How to get it done?

**Comment by Omicron666** [comment]
The problem is not listing lowest price.
Pages are downloaded in a few seconds.
jQuery is bottlenecking DOM/jQuery objects manipulation.

**Comment by Botan626** [comment]
Is jQuery a part of SEE or Steam itself.

Is there anything can be done re this?

At present time I do like this:

1. Disable SEE.
2. Install SIH.
3. Create market orders with SIH.
4. Uninstall SIH.
5. Enable SEE.
6. Relist overpriced items with SEE if needed.
7.  Disable SEE for possible trades.

**Comment by Nuklon** [comment]
jQuery is part of both SEE and Steam. But I could finally reproduce this in the trade offer window, please try the latest build.

**Comment by Botan626** [comment]
Works fine with the trade offers, but still lagging perfoming inventory actions.

**Comment by Nuklon** [comment]
Please check again if this helps on the inventory. This is about as good as I can get it I think.

**Comment by Botan626** [comment]
Still takes 13-15 seconds to load info on a card to sell.

**Comment by Nuklon** [comment]
Do you have a public inventory? Please give me a link so I can try it out myself on yours.

**Comment by Botan626** [comment]
Here you go:

http://steamcommunity.com/id/Botan626/inventory/

**Comment by Nuklon** [comment]
If I have SEE disabled it's also very slow on your inventory, with or without it's the same.

**Comment by Botan626** [comment]
Try to search for "jet racing" items in my inventory, for example.

Once the images are loaded, the selection between them takes nothing (time) with SEE disabled (same with SIH).

If SEE enabled, it's around 15 seconds.

**Comment by Nuklon** [comment]
Takes 5 seconds without SEE in all browsers here, well, except Edge, which seems to give up after a minute or so.
If all images are loaded it takes <1 second in Firefox and Chrome, with or without SEE.

**Comment by Botan626** [comment]
>>Did you force SEE to update?  --  Of course, 4.8.0 installed.

For me it takes 12-15 seconds. Shift selection takes twice longer.

**Comment by Nuklon** [comment]
OK, well, I can't reproduce it, I don't have such a big inventory myself but just browsing your inventory from the outside is as fast with as it is without. You'll have to see what's causing it yourself.

**Comment by Botan626** [comment]
You'll have to see what's causing it yourself.  ---  I have no idea how this could be done.

**Comment by Botan626** [comment]
Plus, you just turned it's functionality off in other people's inventories, and I have no issues browsing strangers' inventories too.

**Comment by Nuklon** [comment]
If you go to this part:

>  // Ignore selection on other user's inventories.
        if (!isOwnInventory)
            return;

make it like this:

>  // Ignore selection on other user's inventories.
      //  if (!isOwnInventory)
            return;

How's the performance then?

**Comment by Botan626** [comment]
I just need to edit it in Tampermonkey  and press floppy disk button?

Well I did this, and it works fast and smooth, though no green buttons appeared there.

I tried this one: https://steamcommunity.com/id/laume_kurai/inventory/

**Comment by Botan626** [comment]
I added you to friends in Steam for conversation.

**Comment by Nuklon** [comment]
You should try it out on your own inventory. What you're missing then should be the quick sell buttons on the right side + inventory selections,  the rest of the script should work completely.
________________________________

**Comment by Botan626** [comment]
I have no sell buttons on the right side, but 3 buttons above inv. are still there. What are inventory selections buttons?

With that done, works fast and amooth.

![see](https://cloud.githubusercontent.com/assets/28785698/26763353/566fc9ac-495a-11e7-8be8-d82db3847664.PNG)

**Comment by Botan626** [comment]
Maybe it has something to do with the currency, Rub?

**Comment by Botan626** [comment]
New info: 

I manually navigated through my inventory to page 80 or so, and during this cards were selected with no trouble and multiple selection worked good.

As soon as I put "jet racing" in the search field, it all crashed, the tab doesn't respond for 3 mins already.

**Comment by Nuklon** [comment]
Unlikely, the buttons above are added elsewhere and that doesn't change, it's just the information on the right side that's different. I'll chat to you on Steam when you're online and see if we can narrow it down.
