### ISSUE TITLE
Is there a way to change default price to sell miltiple items?

### ISSUE THREAD

**Issue by SakhJack** [Nuklon/Steam-Economy-Enhancer#2]
and if not can it be implemented?

I want to sell it for minimum amount of **sell** order -0.01

what determines default price now?

Thanks

**Comment by Nuklon** [comment]
Currently it uses a combination between history and sell orders. If there are items sold within the last 12 hours, it uses the average price of that (if it exceeds the lowest sell order). 
If not, it uses the sell orders and then adds -0.01 to the price (default).
This is currently the only available way to list prices.
I don't want to make it too complicated with adding tons of extra options, but I'll consider adding it, I'll have to think about it.
