### ISSUE TITLE
Bug: Sell options appear even it's not your inventory

### ISSUE THREAD

**Issue by Connor37** [Nuklon/Steam-Economy-Enhancer#20]
![image](https://cloud.githubusercontent.com/assets/8341213/26760803/f7a33ac2-4921-11e7-9635-ba3abb40a294.png)

**Comment by Botan626** [comment]
What is not in your inventory?

**Comment by Connor37** [comment]
> What is not in your inventory?

It is not about what is in my inventory. This is my friend's inventory but the sell options still appear.

**Comment by Botan626** [comment]
Misread, sorry.

**Comment by Nuklon** [comment]
Yes, I've noticed that, will fix it.
