### ISSUE TITLE
These items cannot be added to the market...

### ISSUE THREAD

**Issue by Botan626** [Nuklon/Steam-Economy-Enhancer#21]
![see](https://cloud.githubusercontent.com/assets/28785698/26781425/1069d69e-49f7-11e7-87e4-18dd61c45ce4.PNG)

Selected 4 items, could not sell them in bulk.

But they've been placed on market one by one.

**Comment by Botan626** [comment]
![see](https://cloud.githubusercontent.com/assets/28785698/26817783/9efaaa1a-4aa0-11e7-9ee0-25e1bbc60f27.PNG)

Again with different game.

**Comment by Nuklon** [comment]
I think you clicked the sell button twice, items are automatically added to a queue so they aren't processed twice. If you click the button twice no items can be added as they are queued already.

**Comment by Botan626** [comment]
But they were not processed for 1st time neither.

**Comment by Nuklon** [comment]
It takes a while to sell the items as the inventory has to be loaded before the items can be sold. As long as you see the item spinner it will be sold. If you have a large inventory it'll take longer.

**Comment by Botan626** [comment]
I will keep looking over this.

**Comment by Nuklon** [comment]
OK, thanks. I think there's some improvement possible in that regard, I'll have to think it over. I have very little time right now but will keep it open.

**Comment by Botan626** [comment]
I will confirm the issue.

I searched in my inventory for Payday 2 items, selected 6 different cards placed randomly, hit 'sell selected' button and that message appeared.

**Comment by Nuklon** [comment]
Can you check if the issue is still there in 4.9.0?

**Comment by Botan626** [comment]
No, but I will say, that there are no check boxes again.

![see](https://user-images.githubusercontent.com/28785698/27004822-1d30058a-4e19-11e7-9630-e2afee24d6cb.PNG)

**Comment by Nuklon** [comment]
Does that only happen when there are no sell orders? Also, which browser are you using? They always show here.
________________________________

**Comment by Botan626** [comment]
I don't know, but there were no sell orders when I made this screenshot.

I use Chrome.
