### ISSUE TITLE
No check boxes.

### ISSUE THREAD

**Issue by Botan626** [Nuklon/Steam-Economy-Enhancer#22]
![see](https://cloud.githubusercontent.com/assets/28785698/26817935/5a3106b2-4aa1-11e7-811d-829a25ca4fa7.PNG)

**Comment by Nuklon** [comment]
Only with awaiting confirmation?

**Comment by Botan626** [comment]
They somehow came back.

**Comment by Nuklon** [comment]
Alright, closing it then for now, if you can reproduce this (so I can reproduce it too) you can comment here or open a new one.
