### ISSUE TITLE
CSS issues with buttons and animations

### ISSUE THREAD

**Issue by Sadzurami** [Nuklon/Steam-Economy-Enhancer#221]
### Describe the bug

After clicking on any button all buttons resizes and it looks weird.
It only occurs on inventory pages other than Steam (753).

On Steam inventory page (753) after clicking any button, progress animation placed not in center.

![image](https://github.com/user-attachments/assets/6fea2738-97c6-439d-bc15-12eccdaa5a63)

I use the latest version from master branch.

### Browser name and version

Chrome 126

**Comment by Nuklon** [comment]
Works OK here, can't reproduce.
