### ISSUE TITLE
2FA listing confirmations

### ISSUE THREAD

**Issue by SeRi0uS007** [Nuklon/Steam-Economy-Enhancer#223]
### Is your feature request related to a problem? Please describe.

I want to add to this userscriptscript the ability to automatically confirm 2FA requests for listing items on the market.

I have a working code (I just need to update it).
And I will send the prepared Pull Request.

Is the philosophy of this project suitable for such a code?

**Comment by woctezuma** [comment]
For info, you could be periodically running `!market2faok` with the ASF plugin [`BoosterManager`](https://github.com/Citrinate/BoosterManager).

**Comment by SeRi0uS007** [comment]
The Pull Request I mentioned has been prepared.
#224
