### ISSUE TITLE
Inventory add change price in getItemOrdersHistogram

### ISSUE THREAD

**Issue by Giza** [Nuklon/Steam-Economy-Enhancer#23]
as here https://gist.githubusercontent.com/Ne3tCode/68a70d0cd2b950816b64c4f9383813a0/raw/steam_market.user.js
'data-tooltip': 'Use mouse scroll to change price'

**Comment by Nuklon** [comment]
What does this do? Please give a better description / screenshot.

**Comment by Giza** [comment]
https://youtu.be/XbHb2C1qB_4

**Comment by Nuklon** [comment]
OK, well, I'll have to think about it, I don't think the way that's done is very clear to the user. There are enough buttons as-is so then I'll have to either add another one or change the current buttons.

**Comment by Nuklon** [comment]
There's a ticker for a while now, closing this.
