### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Botan626** [Nuklon/Steam-Economy-Enhancer#24]
1. "Select all" button doesn't work;

2. No color backlight for listings;

3. Relisting for overpriced items doesn't work.

**Comment by Botan626** [comment]
So it all worked for a while, then I sold couple of items, reloaded market page and that issues came back.

**Comment by Botan626** [comment]
Comp was restarted, these issues still exist.

**Comment by Nuklon** [comment]
Can't reproduce, it is all working OK here.

http://i.imgur.com/t3zqUgA.gifv

**Comment by Botan626** [comment]
Re-installed script just now, didn't help.

**Comment by Botan626** [comment]
It works on item's page though.

![image](https://user-images.githubusercontent.com/28785698/27084301-07a78976-5054-11e7-800a-8df0880fd723.png)

**Comment by Nuklon** [comment]
Are the items still loaded on the market page or doesn't that work either?

**Comment by Botan626** [comment]
Yes, the items are there.

**Comment by Botan626** [comment]
I have buy orders too.

**Comment by Nuklon** [comment]
It was Chrome again.

**Comment by Botan626** [comment]
I've got to say, still doesnt work after update.

**Comment by Nuklon** [comment]
It works on my Chrome installation, selection, color and relist.

**Comment by Botan626** [comment]
I'm not making it up.

**Comment by Nuklon** [comment]
Me neither :) http://i.imgur.com/k1TsJM2.gifv
I'll talk to you later on Steam, gotta do some other things first.

**Comment by Botan626** [comment]
Send me mssg even if I'm offline.

**Comment by Botan626** [comment]
Well now, all of a sudden, it's working again.

What's going on?

**Comment by Botan626** [comment]
Ain't working again!

**Comment by Botan626** [comment]
Nuklon, pls examine this.  Nothing changed, 20 mins ago was good, now it's off.

**Comment by Nuklon** [comment]
No time at the moment. What you can do already is see if you can narrow it down, when does it work and when not. It's really strange that it works occasionally.
________________________________

**Comment by Botan626** [comment]
No, I can't. From my point of view it shuts down randomly, like it's all good, then market page reload amd it's all gone.

**Comment by Botan626** [comment]
It's working again!

Been selling items from inventory, opened market page and saw it's running. So nothing special did happen, as far as I can say.

**Comment by Botan626** [comment]
LOL.

Crafted a badge, sold one myst card, opened market page and it's sleeping again!

**Comment by Botan626** [comment]
It's like a roller coaster. 

Relisted an item --> shut down.

**Comment by Connor37** [comment]
I can confirm this too.

**Comment by Nuklon** [comment]
Yes, thank you, not sure why that isn't set (it is here all the time). Will add another check for it.

**Comment by Connor37** [comment]
Still not working for me. Same thing in the console.

**Comment by Nuklon** [comment]
Please add me on Steam so I can check it out.
