### ISSUE TITLE
Uncaught SyntaxErrors

### ISSUE THREAD

**Issue by Royalgamer06** [Nuklon/Steam-Economy-Enhancer#30]
![](https://i.imgur.com/qjYGNVg.png)
![](https://i.imgur.com/U6bC5qG.png)
![](https://i.imgur.com/2NfDHw3.png)

This happened when loading (and automatically relisting) market items. It seems to happen at this card: http://steamcommunity.com/market/listings/753/582980-%3F%3F%3F%3F

**Comment by Nuklon** [comment]
Histogram itself looks undefined?
Any more information about the syntax error?
________________________________
From: Royalgamer06
Sent: Mon Jun 19 16:38:07 GMT+02:00 2017
To: Nuklon/Steam-Economy-Enhancer
Cc: Subscribed
Subject: [Nuklon/Steam-Economy-Enhancer] Uncaught SyntaxErrors (#30)


[https://camo.githubusercontent.com/b281f9dce380a66ee67c8e6dda78f76d3b23c1f3/68747470733a2f2f692e696d6775722e636f6d2f716a59474e56672e706e67]<https://camo.githubusercontent.com/b281f9dce380a66ee67c8e6dda78f76d3b23c1f3/68747470733a2f2f692e696d6775722e636f6d2f716a59474e56672e706e67>
[https://camo.githubusercontent.com/34e43cddc29a212c3b4fc3829de304d576089c72/68747470733a2f2f692e696d6775722e636f6d2f553662433571472e706e67]<https://camo.githubusercontent.com/34e43cddc29a212c3b4fc3829de304d576089c72/68747470733a2f2f692e696d6775722e636f6d2f553662433571472e706e67>
[https://camo.githubusercontent.com/071a2497155db2e138b43f1350b6c516a1915ba2/68747470733a2f2f692e696d6775722e636f6d2f324e66444877332e706e67]<https://camo.githubusercontent.com/071a2497155db2e138b43f1350b6c516a1915ba2/68747470733a2f2f692e696d6775722e636f6d2f324e66444877332e706e67>

This happened when loading (and relisting) market items.

**Comment by Royalgamer06** [comment]
I gave all the information there was
