### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Botan626** [Nuklon/Steam-Economy-Enhancer#31]
1. 
![image](https://user-images.githubusercontent.com/28785698/27443603-4ac532c4-577c-11e7-959e-b5e566c3068f.png)

2. Shift selection doesn't work for buy orders.

**Comment by Nuklon** [comment]
How did you add these cards to the market? Which button, etc.
________________________________
From: Botan626
Sent: Thu Jun 22 17:55:29 GMT+02:00 2017
To: Nuklon/Steam-Economy-Enhancer
Cc: Subscribed
Subject: [Nuklon/Steam-Economy-Enhancer] Issues (#31)


  1.

[image]<https://user-images.githubusercontent.com/28785698/27443603-4ac532c4-577c-11e7-959e-b5e566c3068f.png>

  1.  Shift selection doesn't work for buy orders.

**Comment by Botan626** [comment]
Manually, pressing buttonds with prices on the right.
