### ISSUE TITLE
Why my item price listed based on highest buy order?

### ISSUE THREAD

**Issue by adifahman** [Nuklon/Steam-Economy-Enhancer#32]
is that intended ?

http://i.imgur.com/wW8orNx.png

**Comment by Nuklon** [comment]
Yes, under one condition. If you have defined a maximum of, let say 20 cents, but there's a buy order for 30 cents, then SEE will always put it on the market for 30 cents and not 20 cents.

**Comment by adifahman** [comment]
oh i see, thanks !
