### ISSUE TITLE
Enhancement: Second lowest price sell button

### ISSUE THREAD

**Issue by to-dr** [Nuklon/Steam-Economy-Enhancer#33]
Is there easy option to replace 
prices.push(parseInt(histogram.lowest_sell_order) - 1);
for like second/third lowest?

**Comment by Nuklon** [comment]
At the moment, not really.

**Comment by Nonickn** [comment]
Hi!
Is there a way to sell all chosen items (not just one) for (-1) of lowest price?

**Comment by Nuklon** [comment]
Yes, you can change 'Calculate prices as' to lowest price, and add -0,01 to the price.

**Comment by Nuklon** [comment]
Changed to custom field.
