### ISSUE TITLE
Select multiple items problem

### ISSUE THREAD

**Issue by solomad** [Nuklon/Steam-Economy-Enhancer#34]
Hi. In Chrome is very complicate to select cards in inventory =(
It's possible to add at Inventory page "Select all from page" button, like is at trade page?

**Comment by Nuklon** [comment]
You can just use shift for multi select.
________________________________
From: solomad
Sent: Fri Jul 21 18:03:45 GMT+02:00 2017
To: Nuklon/Steam-Economy-Enhancer
Cc: Subscribed
Subject: [Nuklon/Steam-Economy-Enhancer] Select multiple items problem (#34)


Hi. In Chrome is very complicate to select cards in inventory =(
It's possible to add at Inventory page "Select all from page" button, like is at trade page?

**Comment by solomad** [comment]
If I use any filter in inventory - Shift selection stops working. I use Chrome, only with Tampermonkey addon

**Comment by Nuklon** [comment]
I can't reproduce that, it works fine in Chrome with Tampermonkey and some other plugins such as uBlock Origin.

![img](http://i.imgur.com/cSPdYaw.png)
