### ISSUE TITLE
Can not relist overpriced items.

### ISSUE THREAD

**Issue by Botan626** [Nuklon/Steam-Economy-Enhancer#35]
![image](https://user-images.githubusercontent.com/28785698/28607037-a6c89342-71e2-11e7-8bf5-03dcdb90c669.png)

P.S. Chrome was updated.

**Comment by Botan626** [comment]
Hello?

Main function aint working.
![image](https://user-images.githubusercontent.com/28785698/28683599-d0298dea-7309-11e7-9f58-91cd9d9504aa.png)

**Comment by Nuklon** [comment]
Yes, Valve changed that if you return item to inventory (only if you placed it on the market), it's changing the assetid. Unfortunately, the only viable solution to this would be to check the inventory for said item, which isn't available on the market page and is also far from ideal. For now you have to disable the automatic relist feature. I hope Valve reverts this change although it seems unlikely.

**Comment by Botan626** [comment]
So relisting feature won't be available in the nearest future.

**Comment by Nuklon** [comment]
Yes, that's correct. Unless Valve reverts it (very unlikely) I'll change the option to automatically remove overpriced listings instead. It's just one extra step (go to inventory afterwards) so not such a big deal.

**Comment by Botan626** [comment]
> It's just one extra step (go to inventory afterwards) so not such a big deal.

No, the beauty of SEE was in that it could do it in auto mode. Going back to to inventory, search there for needed items, then manually list them again is a pain in the ass.

**Comment by Nuklon** [comment]
Unless Valve fixes this, it won't come back, sorry. Technically it's not possible in a reliable way.
________________________________
