### ISSUE TITLE
Relisting issues.

### ISSUE THREAD

**Issue by Botan626** [Nuklon/Steam-Economy-Enhancer#36]
I noticed you returned relisting of overpriced itmes feature. 

It workes good with some items, but with other items not.

![image](https://user-images.githubusercontent.com/28785698/28756492-373da9f6-7578-11e7-8a05-71f9ce4b459f.png)

**Comment by Nuklon** [comment]
Always the same item that's causing problems? If so, please send one over so I can try it out.
________________________________
From: Botan626
Sent: Sun Jul 30 21:41:35 GMT+02:00 2017
To: Nuklon/Steam-Economy-Enhancer
Cc: Subscribed
Subject: [Nuklon/Steam-Economy-Enhancer] Relisting issues. (#36)


I noticed you returned relisting of overpriced itmes feature.

It workes good with some items, but with other items not.

[image]<https://user-images.githubusercontent.com/28785698/28756492-373da9f6-7578-11e7-8a05-71f9ce4b459f.png>

**Comment by Botan626** [comment]
No, different items.

**Comment by Nuklon** [comment]
But do the same items keep not working if you list them again at a too high price?
________________________________

**Comment by Botan626** [comment]
Seems doesn't work with emoticons.

**Comment by Nuklon** [comment]
Alright, can you send me one to try it out? I don't have any.
________________________________

**Comment by Botan626** [comment]
sent you :lionsmile:

**Comment by Botan626** [comment]
When you will send it back to me?

**Comment by Nuklon** [comment]
Most likely this weekend, my time is limited during the week. Seeing how little it's worth you might consider just donating the item so I have something to test it with for the future (e.g., I still have some unsellable items so I know it doesn't break that functionality). If you don't want this it's OK too, just give me some time to resolve it 👍

**Comment by Botan626** [comment]
In my opinion the developer should have all needed instruments to test his product.

And this emot is random, other didn't relist too.

But my Q was about setting the time borders, and I'm ok with this weekend :)

**Comment by Nuklon** [comment]
> In my opinion the developer should have all needed instruments to test his product.

Please remember, this is a free script and not a paid product. I simply don't have all possible items to test everything out and as such, from time to time I require something from the user in order to fix it.

**Comment by Botan626** [comment]
Yes, I remember this, and I did provide you with the emot., because I'm interested in having working product too.

**Comment by Nuklon** [comment]
You made it sound like I should have everything and do everything the user wants, this is not the case. SEE is just a script I provide for free to the community as I thought it'd be a good addition to what's available. However, it also ends there. For example, to make it absolutely clear, I'm not going to personally pay for items I don't have it order to fix an issue that I personally don't have 😄

**Comment by Botan626** [comment]
There are items that don't want to behave for a prolonged period of time? 

Then again, I sent you just a random emot.
