### ISSUE TITLE
SEE can't fetch prices.

### ISSUE THREAD

**Issue by Botan626** [Nuklon/Steam-Economy-Enhancer#37]
For this item:
![image](https://user-images.githubusercontent.com/28785698/29273569-6ddc073c-810d-11e7-8295-59f3e11baaa7.png)

**Comment by Nuklon** [comment]
Probably because of the ??? in the name. Can't test this myself as I don't have anything anymore with weird names.

**Comment by Botan626** [comment]
Sent you this item.

**Comment by Botan626** [comment]
You going to send me the item back?
