### ISSUE TITLE
Compatibility With This Skin

### ISSUE THREAD

**Issue by Royalgamer06** [Nuklon/Steam-Economy-Enhancer#4]
Hi, thanks for this amazing userscript. I have one small request.
I am using [this custom style](https://userstyles.org/styles/117058/flat-steam-ui) for Steam, but I always have to disable it when using your script, because it hides your UI.
Would it be possible to make it compatible with this skin?
That would save me a few clicks in the future.
Thank you!

**Comment by Nuklon** [comment]
No, sorry, this is out of the scope of SEE.
