### ISSUE TITLE
WTF?!

### ISSUE THREAD

**Issue by Botan626** [Nuklon/Steam-Economy-Enhancer#40]
I sent you an item for testing purposes.

Previously I made it clear with you that I want my items back.

Now you didn't sent it back + I don't see it in your inventory + you don't respond for 2 weeks, so I want to get some explanation from you re this situation.

**Comment by Nuklon** [comment]
As I've already said to you, the item was accidentally put on market. Please stop spamming constantly, it's very annoying.
