### ISSUE TITLE
Inventory selling hangs upon market 500 error

### ISSUE THREAD

**Issue by MikeLund** [Nuklon/Steam-Economy-Enhancer#42]
Selling all items from inventory on Chrome (600 items, none with weird names).
Console got two errors after selling ~170 items:

`Failed to load resource: the server responded with a status of 500` (from /market/sellitem/)
and also:
```
VM227:2263 Uncaught TypeError: Cannot read property 'message' of undefined
    at eval (eval at E_c (:3:298), <anonymous>:2263:47)
    at Object.error (eval at E_c (:3:298), <anonymous>:1643:24)
    at i (eval at E_c (:3:298), <anonymous>:6:28017)
    at Object.fireWith [as rejectWith] (eval at E_c (:3:298), <anonymous>:6:28783)
    at A (eval at E_c (:3:298), <anonymous>:8:14060)
    at XMLHttpRequest.eval (eval at E_c (:3:298), <anonymous>:8:16323)
```

After it just sat there spinning on "Processing 600 items".

Sorry if this seems like lazy-bug report, but I don't know how to get more debugging info from it. Hope this helps and thanks a lot for your work, it's appreciated to have a nice alternative to SIH.

PS: I'd suggest to not use the Github `/master/` links in your requires - use the raw commit ID, or can be headaches for you in the future to debug if someone pushes non-backwards compatible depend :)

**Comment by Nuklon** [comment]
Does this always happen with the same item? Also, you'd have to accept the current listings soon anyway, Steam only allows you to have 200 in the 'in need of verification queue'.
About the /masters/, certainly possible. Where possible I've used releases but not everyone uses that unfortunately.

**Comment by MikeLund** [comment]
If I reloaded page, it proceeded without problem, so I think it's just some uncaught exception with the status response?

Item count not a big problem since I have confirmations going automatically, but good thing to keep in mind (could catch message and have it pause listing in such a case).

Re: github, it actually is possible without versioning, I think. If you open first lib for example, https://github.com/kapetan/jquery-observe/blob/master/jquery-observe.js , then click the commit ID(ca67b73), then click "View" on the js, then click "Raw", you get this link: https://raw.githubusercontent.com/kapetan/jquery-observe/ca67b735bb3ae8d678d1843384ebbe7c02466c61/build.rb
which would function pretty much the same as release tagging. Just so you know, but of course not important.

**Comment by Nuklon** [comment]
I know where the message property is used, I think it's a Steam issue, but should be fixable. I'll also address the libs, you're totally correct about it, wasn't really aware of that possibility :)

**Comment by Nuklon** [comment]
Should all be fixed.
