### ISSUE TITLE
"The value to add to the calculated price" should be set to 0 by default. 

### ISSUE THREAD

**Issue by ZombieTaco** [Nuklon/Steam-Economy-Enhancer#43]
This should be 0 by default. 

also the minimum and maximum price for items seems redundant.

**Comment by Nuklon** [comment]
No, the minimum and maximum price is not redundant, I use it all the time. I don't want to sell items for less than 4 cents (why bother), nor does it make sense to put trading cards on the market for ~1800EUR (max Steam allows), so you add a max price for it. The default is -0,01 to sell it for a lower price than the current listing (which is what most people wanted), but it'll still respect the min and max.

**Comment by ZombieTaco** [comment]
I can see the minimum and maximum somewhat being upto preference.

but under cutting card prices is what and will drive card prices down. I still think the default should be 0. 

I am grateful however of a somewhat replacement of SIH.

**Comment by Nuklon** [comment]
That's certainly a fair point, I'll think about it.

**Comment by Nuklon** [comment]
I've changed this to 0.00, will upload a new version later.

**Comment by ZombieTaco** [comment]
neat :) thanks
