### ISSUE TITLE
Confusing item selection borders

### ISSUE THREAD

**Issue by MikeLund** [Nuklon/Steam-Economy-Enhancer#45]
See example from TF2 inventory:

![screen shot 2017-09-22 at 12 36 06](https://user-images.githubusercontent.com/17044744/30741049-ad62d85a-9f93-11e7-9c4c-a12f198930cf.png)

The 2nd and 3rd items are selected for selling, the 4th one isn't -- but coloring is similar, and can be confusing. Think it could be good to use a dotted border if possible, like SIH.
![screen shot 2017-09-22 at 12 49 16](https://user-images.githubusercontent.com/17044744/30741282-7d6cbb1a-9f94-11e7-8eef-62a46836cf14.png)

-- Additionally, it would be useful to have a counting on the "Sell Selected Items" button in inventory, to reassure the user how many items are going to be sold.

HTH!

**Comment by Nuklon** [comment]
I rarely use TF2 inventory, but I see it indeed, I'll change the selection border. I don't know if the number of selected items are always easily available, I'll take a look at that.

**Comment by Nuklon** [comment]
I've this fixed as well (it's now white dashed).
