### ISSUE TITLE
Suggestion - don't check price for our items that are at lowest possible Steam price already

### ISSUE THREAD

**Issue by Omicron666** [Nuklon/Steam-Economy-Enhancer#46]
Hello,
This a enhancement suggestion that should speed up script on main page and help updating item prices that are too high faster, especially if most of your items still on sale are at 0.03€ (for EU) :
Don't check price for our items that are at lowest possible Steam price already.
And you can assume there are other items with same price. (that your items at 0.03€ aren't unique items)
Cases where you are the only seller for a 0.03€ item rarely last long anyway.

**Comment by Nuklon** [comment]
Do you mean: don't check prices if you have it listed at minimum price? Your description isn't very clear to me.
________________________________
From: Omicron
Sent: Fri Sep 22 14:12:44 GMT+02:00 2017
To: Nuklon/Steam-Economy-Enhancer
Cc: Subscribed
Subject: [Nuklon/Steam-Economy-Enhancer] Suggestion - don't check price for our items that are at lowest possible Steam price already (#46)


Hello,
This a enhancement suggestion that should speed up script on main page and help updating item prices that are too high faster, especially if most of your items still on sale are at 0.03€ (for EU) :
Don't check price for our items that are at lowest possible Steam price already.
And you can assume there are other items with same price. (that your items at 0.03€ aren't unique items)
Cases where you are the only seller for a 0.03€ item rarely last long anyway.

**Comment by Omicron666** [comment]
Yes.
Sorry for verbosity.
You probably already know minimum price are region or currency related.

**Comment by Nuklon** [comment]
While that might sound like a good idea, in my usage with the market I'm no fan of such a change. The reason is that sometimes an item is listed very cheaply, with new games, then some people buy the item and the price gets increased again. Surely with 500 sellers of 3 cents that's very differently but to store all that data in cache would bloat everything too much I think.
________________________________

**Comment by Omicron666** [comment]
This case doesn't happen :-) 
If your item is listed at minimal price of 0.03€, prices aren't getting increased before you sell your own item !

**Comment by Omicron666** [comment]
There is nothing to store in cache.

**Comment by Nuklon** [comment]
Well, underpriced check doesn't really take your listing into account. For example, you list it at 3 cents, the next person lists it at 6 cents, then you're underpriced. This information can only be accessed by actually getting the price information.

**Comment by Omicron666** [comment]
I don't see how you would be underpriced if it was at 3 cents in the first place, according to what your script calculated.

If there are 500 other 3 cents sellers, it saves you time.  Script is not going to relist your item.
If there are 5 other 3 cents sellers, script is not going to relist your item.
If you are the last 3 cents seller, your item is likely to be bought before your have time to relist it. (and you should not care about it as script set it at 3 cents in first place, that means there were at least other 4 cents items, in 99.9% of cases)
