### ISSUE TITLE
Option to refresh the market pricing

### ISSUE THREAD

**Issue by CaitSith2** [Nuklon/Steam-Economy-Enhancer#5]
Would it be possible, beside the buttons for selling the cards at various prices, to add a button to refresh the market, and subsequently, the buttons.   Sometimes, I go and sell card for the highest available buy order price,  there is only one of that price.  confirm,  doesn't sell.   Turns out, somebody beat me to that buy order price.  so I go and remove it,  then go back in order to set an updated price, but because it is using a cached result, I don't see the updated buy order listings.   It would be nice to be able to refresh them.

**Comment by Nuklon** [comment]
You can open a new tab or window and the cached results should not persist. With caching it's always a bit tricky. In this instance though I don't see any reason to cache the quick sell buttons and I'll rewrite it so clicking on a card always gets the latest information. 

Ideally you should just go to the market and use the _Relist overpriced_ button. Of course, that's also cached but it'll save you from having to do everything manually.
