### ISSUE TITLE
Userscript is not retrieving prices on incoming offers.

### ISSUE THREAD

**Issue by mausername** [Nuklon/Steam-Economy-Enhancer#51]
If you have an incoming trade offer the userscript doesn't seem to retrieve the prices of the items, it only shows "Number of items: 30, worth 0.00"

The same happens if the items are auto-added to the trade window using steamtradematcher script.

**Comment by Nuklon** [comment]
I can confirm this issue, it used to work, so I'll take a look at what changed.

**Comment by Nuklon** [comment]
This is fixed by Valve. It works in Chrome and Firefox again.

**Comment by Nuklon** [comment]
Yes, this is now also possible in the tradeoffer window as Valve added the inventory. should be fixed now.
