### ISSUE TITLE
Median Sale Prices graph isn't displayed properly.

### ISSUE THREAD

**Issue by Crimson53v** [Nuklon/Steam-Economy-Enhancer#52]
When using this userscript the graph appears empty, if i zoom in the entire graph is condensed into a single line on jan 1.

chrome version 61.0.3163.100
Tampermonkey 4.4
Economy-Enhancer 6.0.1

(This is my first time using this script)

**Comment by Nuklon** [comment]
I don't think this is related to SEE, nothing is done with the graph. It also works OK here.
