### ISSUE TITLE
How to sell itens in bulk

### ISSUE THREAD

**Issue by Schknheit** [Nuklon/Steam-Economy-Enhancer#53]
Hello, how can I sell my itens in my own price in bulk? I can only sell in bulk for a already defined price.

**Comment by ZombieTaco** [comment]
you could set the minimum to your desired price (if its constant, other wise the calculated price is what you're after), but the chances of your cards selling higher than the lowest price is very low, and selling lower than the lowest price is stupid. @Schknheit

**Comment by Schknheit** [comment]
I mean @ZombieTaco in SIH I could sell 100 items setting my own price, but in this extension, I dont even know where to start.
