### ISSUE TITLE
Feature request: total value

### ISSUE THREAD

**Issue by midatool** [Nuklon/Steam-Economy-Enhancer#55]
Can you add the total value (with and without the Steam commission) when listing multiple items and also the total value of the items already listed on the market? A graph with the items sold and bought would be nice too to track profit.

Nice job, keep going.

**Comment by Nuklon** [comment]
The graph is a bit too much for SEE I think, but the other total values might be possible to add somewhere. Have to think about where this might be a good fit.

**Comment by Nuklon** [comment]
Added this for the market. Inventory isn't really possible as SEE only checks prices for the currenty inventory in order to not spam too much to Steam.

**Comment by midatool** [comment]
Thank you for considering my request.

Unfortunately, the total value on the market is not working. It is considering the values as NaN.

The inventory does not really need it, I think I mispronounced. What I meant was that would be nice to have the total value of the listing I just created. Check the example on the link: https://imgur.com/t9wYE6l

Also, would you be interested in doing a job for me? Obviously, I would pay you.

I appreciate your attention.

**Comment by Nuklon** [comment]
Does price checking on the market work for you? The code for retrieving the price from a listing is identical. The other information is something I can add, I like it.

**Comment by Nuklon** [comment]
Both added.

**Comment by midatool** [comment]
Everything is working fine now, including the total value on the market.

If you are interested in doing a paid job for me involving Steam, please leave a way to contact you or contact me at lucasabcarvalho@gmail.com.

Thanks!

**Comment by Nuklon** [comment]
Glad to hear, feel free to add me on Steam to discuss (id = Nuklon).

**Comment by midatool** [comment]
I just sent the friend invitation. Thanks!
