### ISSUE TITLE
Feature Request: Trade offer price check at tradeoffers list page.

### ISSUE THREAD

**Issue by KazeZlat** [Nuklon/Steam-Economy-Enhancer#57]
An option to get trade offer price in the list without opening its page could be really handy. Can you add that too please?

**Comment by Nuklon** [comment]
Yes, it would be, but inventory is not available at overview page. That make it pretty hard to add.
On Oct 21, 2017, at 15:37, KazeZlat <notifications@github.com<mailto:notifications@github.com>> wrote:

An option to get trade offer price in the list without opening its page could be really handy. Can you add that too please?
