### ISSUE TITLE
manual price on multiple items

### ISSUE THREAD

**Issue by Gucek** [Nuklon/Steam-Economy-Enhancer#58]
any way to do that? maybe by making that price with blue-background clickable+editable? (in such case after confirming it should update displayed price for other same items)

**Comment by Nuklon** [comment]
No, this is not possible. The main reason is that it wouldn't integrate that well with the rest. I personally also can't see a good reason why this would be useful. Ideally you want SEE to automate the prices. If you're unhappy with its pricing you should configure it differently.
On Oct 29, 2017, at 18:05, Gucek <notifications@github.com<mailto:notifications@github.com>> wrote:

any way to do that? maybe by making that price with blue-background clickable+editable? (in such case after confirming it should update displayed price for other same items)

**Comment by Gucek** [comment]
the thing is: this price automation does work for me in 3% of my use case. I don't need to sell items immediately - I put them for sell, judging the price on chart for last month. assuming I have 10 - I will set 2 for "crazy-high" price that it sold last month, 3 for lower and another five for "above current". most of them will sell eventually - I'm not in a hurry. few months later I adjust prices for things that didn't sell.

also - when selling multiple - user has NO indication what price it will sell using the tool (if adjusted in options).

**Comment by Nuklon** [comment]
Unfortunately there's not really an easy option to manually add prices (which means you/user would have to check all items one by one again, which is kinda against the purpose of this script). What you can use for your purpose is the buttons on the right side (which also have higher prices). 

There's indeed no indication before it is listed, this is because SEE is async and it only loads the required data from Steam when necessary to prevent floading.

**Comment by genesix-eu** [comment]
I would also like this feature. I want to choose price and I don't need to sell it immediately.

**Comment by svefn** [comment]
+1 very useful feature. can't find similar functionality since SIH steam inventory helper.

**Comment by Geralt28** [comment]
Even better would be possibility to set price formula somehow. I mean I dont wat to sell on lower possible price but f.e. average price or higher price for which it was sell in last XX days minus 0,0X cents

**Comment by WhitestWolf** [comment]
The reason I would also want this update is that I have 200 items in my tf2 inventory that are on sale for 0.03 euros each: specialty crates that are no longer obtainable in any way other than through the market and trading

Your script has helped me sell a lot of items before but it doesn't work for these at all

It sets them all to 0.05 euros in which case I would receive 0.03 for each of them but there are more than 10000 of them on the market going for 0.03 euros

This also happened with other items that I tried to mass sell

Being able to manually set the price would make it work and doing it manually for each item would take ages and thanks again for making this script it is a great substitute for the Steam Inventory Helper

**Comment by Fleshus** [comment]
First of all thank you for providing this plugin for free to the public.
But for me too it is this feature that would be most useful to me.
Also it seems to me that it is already possible to do it according to certain conditions:

1. Enter the desired sale price BEFORE and AFTER selecting the items you wish to sell.
2. Select items 1 by 1 with CTRL and not with SHIFT.
3. Check that each selected item is considered by the plugin and that the features appear at the bottom right.
It's not an infallible technique but in any case I'm pretty sure it's possible. Still, it's not very practical, it should work properly.

**Comment by akelsch** [comment]
+1, I have to disable the script and activate the Steam Wizard plugin every time to do that

Why shouldn't it be possible to set a fixed/constant price in a dialog box or something similar?

**Comment by Nuklon** [comment]
> +1, I have to disable the script and activate the Steam Wizard plugin every time to do that
> 
> Why shouldn't it be possible to set a fixed/constant price in a dialog box or something similar?

If you want such a feature, feel free to submit a PR for that.

**Comment by akelsch** [comment]
@Nuklon check out the PR please

I did not build a dialog box though. It uses some mechanism Valve provides to mass sell trading cards.

**Comment by Nuklon** [comment]
I think that is fine, there's no need to really repeat what's already implemented. I've just put it to a dialog as it's a little easier to see now what you've tried to sell manually.
