### ISSUE TITLE
steamcommunity.com/market

### ISSUE THREAD

**Issue by Royalgamer06** [Nuklon/Steam-Economy-Enhancer#6]
When I load the market and checked the log, I noticed this:
![](https://i.imgur.com/VqMPeZ9.png)

I got this a lot and there are a few things that stood out for me. One being that error you now 'handle' using try-catch. I don't know how important that is for the functionality of the script, but I get that error a lot and it doesn't look good tbh. Another thing, which I may be wrong about, is that the script says the price is too high even though the prices are the same. I also sometimes get a 502 error when quering a deletion of a listing, which I am not sure if you're handling that correctly, because it still gets green and deleted from the market listings view. 
![](https://i.imgur.com/aMEiyHh.png)

Another great thing would be if you could make this script compatible with Enhanced Steam. It's really annoying that I keep having to turn things off every time I want to use your script, like the custom skin issue. But this time it's about something a half a million steam users use.

Don't get me wrong. I don't want to criticize your script. I think it's actually well coded and awesome. I just want to report some issues/bugs I think your script may have, so you can use my feedback to improve it even more. Keep up the good work!

**Comment by Nuklon** [comment]
If setting the storage fails, it doesn't matter, everything just continues and works OK as it's just to cache the data for another check. Firefox's session storage is unlimited (well I guess until you run out of space), whereas Chrome's limit is 5MB. Also, catching the exception seems the only way to check if there is space left. I don't think there's another way to store more data, I've looked at some alternatives in the past but either it's only for a specific set of browsers, or it doesn't work well.

Regarding the market check, does that happen on relist or on delete? Green on delete should only work if it's actually deleted, otherwise it should be colored red. For relisting it can get removed if a relist fails but the delete works (in order to relist it has to remove the item first, then create a new listing).

**Comment by Royalgamer06** [comment]
Well, either you could make this into an extension or use `var isChrome = !!chrome;` and [this](http://stackoverflow.com/a/37277426)` for Chrome. You have to be browser specific on this issue. 

It happened when removing listings. I might not have seen it correctly. At one point I did see it turn red, but other times I just saw it getting removed while I saw this 502 error in the console.

What about the compatibility with other scripts/skins?

**Comment by Nuklon** [comment]
I'd rather not make it into an extension, I prefer userscripts as for me it's easier to maintain.
I'll check out that other storage stuff though. Having more space available is something that's welcome, although it seems it's permanent storage instead of session storage, so I'll have to see how can I adapt it to that.

Regarding compatibility with other scripts and skins, you're welcome to create a pull request for it. I don't know what is causing in-compatibility as I don't use anything else.

**Comment by Nuklon** [comment]
Can you check the latest version? It should now use IndexedDB for caching. I think I also fixed that market delete bug. I also changed how the pricing is retrieved for overpriced items, which should improve the compatibility with (other) scripts that insert custom classes. 

If there's anything broken with other extensions/scripts, please test it out and create a pull request for it (also make sure it works without them). I don't mind having more compatibility as long as it keeps the code maintainable.

**Comment by Royalgamer06** [comment]
I was testing with MS Edge now, and it doesn't seem to support the `includes` function (line ~1427).

**Comment by Royalgamer06** [comment]
Same with chrome.

**Comment by Royalgamer06** [comment]
BTW, this is what is happening with Steam Enhanced:
![](https://i.imgur.com/s4bDvBg.png)

**Comment by Royalgamer06** [comment]
Test 1 results on Chrome:

1. I waited for the results for all my 772 listings. The console log looked very good! Only 2 [503 errors somewhere at the end](https://i.imgur.com/aYkOKy6.png). There were no storage limit errors in the log!

2. Now when I tried to select overpriced (relist overpriced doesn't work, due to issue from above), it didn't work because of some conflict with enhanced steam. I had to come up with some own code `jQuery("div[id*=mylisting_]:not(:has([style*='background: rgb(73, 100, 36)']))").each(function() {
jQuery(this).find(".market_select_item")[0].checked = true;
});` to select over- and underpriced. However, again, pressing "Remove selected" didn't work due to Enhanced Steam conflict unfortunately. Thus, I had to disable enhanced steam, refresh the page and start over. Luckily, this time it went slightly faster, probably due to the caching mechanic. 

Test 2 results follows.

**Comment by Royalgamer06** [comment]
Test 2 results on Chrome:

1. Same scenario as test 1. No errors at all!

2. Selecting overpriced works as expected. Removing selected also works as expected. No errors at all!

Disclaimer: After the first post of this issue, I reinstalled windows. However, I am using the exact same extensions and userscripts as before. But overall the environment/situation may be a bit different.

**Comment by Nuklon** [comment]
Alright, I think I fixed all issues (including Enhanced Steam). ES is extremely slow (or maybe just Chrome is) but it seems to work now, please check 👍

**Comment by Nuklon** [comment]
Those 503 errors are a bit strange btw, it usually means that you make too many requests at once. It's not such a big issue as I check for it and wait longer with checking the next listing. I've also seen it happen with items not yet listed, although that usually throws a different error.

Regarding the caching, if you refresh the current page (F5) it should almost immediately detect all prices it previously scanned. It then continues where it was (if any).

You have a lot of listings btw, I thought I had a significant number with ~300 👍

**Comment by Royalgamer06** [comment]
You should add a check if the user is logged in, otherwise you get things like this:
![](https://i.imgur.com/5wLGD1t.png)

**Comment by Royalgamer06** [comment]
Also, could you change the 'select all' to 'invert selection' or something, because once you pick select all, you kinda have no choice to remove the check one by one, if you want to undo it.

**Comment by Royalgamer06** [comment]
BTW Huge thanks for the updates!

**Comment by Nuklon** [comment]
I already wanted to add a deselect all button already so I've just added it. I also made the `Remove selected` async, just like the rest and have fixed the logged in too. Thank you for the reports and testing, I appreciate it 👍
