### ISSUE TITLE
1) Not showing price history 2) How to set up a highest price during a period of time for autoselling

### ISSUE THREAD

**Issue by AxJ11** [Nuklon/Steam-Economy-Enhancer#60]
Hi,

I got one issue and one question.
1) Not showing price history 
   When I click on one card to sell in my Steam inventory, it always shows price history.
   Yesterday, after I install SEE, it disappeared!  But the price history graph of cards I'm selling in market is 
   fine.
   https://i.imgur.com/9RIr4CA.png
2) How to set up a highest selling price during a period of time for autoselling
    Like this:
    https://i.imgur.com/rDEHPXI.png
    Is it possible to have settings to achieve this?

    Thank you for taking time reviewing this.

**Comment by Nuklon** [comment]
1.
That should work just fine (at least it does on Firefox and Chrome here). Sometimes Steam is buggy again and it might not work, try Ctrl+F5).

2.
Currently only the last 12h is used for history based prices. It'd be nice to have this configurable to some degree. I know there's at least 24h of data available for most items, I'll take a look at this later to check out how much history is actually available.

**Comment by AxJ11** [comment]
About 2. highest selling price, 
how to set up highest price according to price history(12h) of each card?
SEE seems take average price as selling price.
Even the maximum average price is still way~~~ lower than highest one during certain period of time.

**Comment by snakecase** [comment]
Interested in 2. too.

**Comment by raecer** [comment]
Same here :)

**Comment by Luckz** [comment]
I'd also be a fan of extending this to 24 or even 36 hours.

**Comment by AxJ11** [comment]
Hi, I still can't do auto-selling with history highest selling price for the designated time period.  :(
Did I do something wrong?

https://i.imgur.com/kBUPBhp.png?1
https://i.imgur.com/AgriWFx.png?1

Thank you for your time.
