### ISSUE TITLE
1) Quicksell buttons are too cluttered 2) Median sale prices not working 3) Useful features

### ISSUE THREAD

**Issue by Canadiancookie** [Nuklon/Steam-Economy-Enhancer#61]
1) I feel I could really do without a number of the quicksell buttons. I've only ended up using the "1 cent less than current selling price" one. The buttons to sell for 5 cents or 10 dollars seem particularly pointless and unusable in most cases.

2) [Speaks for itself.](https://i.imgur.com/b2rxxpb.png) It refuses to show up with the script enabled. Works fine disabled.

3) I come from SIH, left because of the whole spyware controversy. There's 3 features i've noticed missing here that I think would be nice.

The more minor ones; a link to the item's market page in inventories, and showing the number of duplicate items you own ([SIH example](https://i.imgur.com/QfTHJdZ.png)). Just tiny QOL additions.

Finally, [historical minimum + best price for games.](https://i.imgur.com/5YgthU7.png) This is a big deal for me; it was an absolutely amazing feature and really helped me see the best current and past prices effortlessly.

**Comment by Nuklon** [comment]
1. Agreed, I have changed it.
2. Fixed.
3. Historical minimum and best price, while being nice, its outside the scope of SEE. For that information you can use different extensions.
