### ISSUE TITLE
Median sale price graph empty

### ISSUE THREAD

**Issue by rluik** [Nuklon/Steam-Economy-Enhancer#62]
In the dialog box when defining price for item to sell, graph is empty

**Comment by Nuklon** [comment]
It's because 
// @require     https://cdnjs.cloudflare.com/ajax/libs/datejs/1.0/date.min.js 
is included and it's breaking Steam's own date.
It's only required at market page but I don't think @require has an option to specify the page. I'll look into another solution for it.

**Comment by Nuklon** [comment]
Fixed.
