### ISSUE TITLE
Dose'nt work with violent monkey/FF57/win10 RS3

### ISSUE THREAD

**Issue by swos0000** [Nuklon/Steam-Economy-Enhancer#63]
don't know why

**Comment by Nuklon** [comment]
It works fine here with Violentmonkey, same configuration.

**Comment by Simfono** [comment]
With FF57 + Greasmonkey also doesn't work. Console error log:
```
Script error:  
TypeError
columnNumber: 1853
fileName: "resource://gre/modules/ExtensionContent.jsm"
lineNumber: 3294
message: "a is undefined"
stack: "@user-script:https%3A//github.com/Nuklon/Steam%20Economy%20Enhancer:3294:1853\nscopeWrapper@user-script:https%3A//github.com/Nuklon/Steam%20Economy%20Enhancer:3294:504\n@user-script:https%3A//github.com/Nuklon/Steam%20Economy%20Enhancer:361:17\n"
__proto__: Object { stack: "", … }
```

**Comment by Nuklon** [comment]
If any errors are listed when using violentmonkey (in console), please add them. It works in Violentmonkey here in Chrome and Firefox just fine, so hard for me to find out what doesn't work.

**Comment by Simfono** [comment]
You are right. Works perfectly with Violentmonkey but doesn't work with GreaseMonkey. Probably something broke down in GreaseMonkey about 4-5 days ago.

**Comment by Nuklon** [comment]
Yeah new grease monkey changed a lot, switch to something else for now.
On Nov 23, 2017, at 19:33, Simfono <notifications@github.com<mailto:notifications@github.com>> wrote:

You are right. Works perfectly with Violentmonkey but doesn't work with GreaseMonkey. Probably something broke down in GreaseMonkey about 4-5 days ago.
