### ISSUE TITLE
The script is not compatible with Enhanced Steam extension

### ISSUE THREAD

**Issue by gizellos** [Nuklon/Steam-Economy-Enhancer#68]
It seems the script is not compatible with Enhanced Steam extension. It's a pity.

I have 459 sell listings and I set the script to show 33 listings on a page. The script shows only 4 pages. The rest of pages are not there. 

If I disable Enhanced Steam, it works normally.

Could you please fix this issue.

**Comment by Nuklon** [comment]
I accept a pr for this but I'm done fixing enhanced steam problems.
On Dec 27, 2017, at 22:22, gizellos <notifications@github.com<mailto:notifications@github.com>> wrote:

It seems the script is not compatible with Enhanced Steam extension. It's a pity.

I have 459 sell listings and I set the script to show 33 listings on a page. The script shows only 4 pages. The rest of pages are not there.

If I disable Enhanced Steam, it works normally.

Could you please fix this issue.

**Comment by gizellos** [comment]
Thank you.
