### ISSUE TITLE
Setting the price

### ISSUE THREAD

**Issue by Whisperstorm** [Nuklon/Steam-Economy-Enhancer#7]
Hi and thanks for the great work on the scipt. Is it possible to create an option to set a constant price manually? The intention is to sell multiple items for a constant price in one swoop.

**Comment by Nuklon** [comment]
Why/where do you want to use that? 
If you really want to you can always go to _Default pricing_ and change the minimum and maximum price to the price you want. Ideally though, you're probably better off with the auto pricing as SEE is trying to make selling easier by reducing the number of actions required :)

**Comment by Whisperstorm** [comment]
True, but the auto pricing doesnt work that well for less popular cards that dont sell in large quantities. And if have the wrong timing youll sell them way below value e.g. when the current lowest price is 0,08 and the second lowest 0,15. But thanks for the hint with the min. and max. A bit inconvenient but works fine with me :D

**Comment by Whisperstorm** [comment]
One more on my wishlist: It would be usefull to see if i have a buy order for the selected card in the bottom right pricing overview.

**Comment by Nuklon** [comment]
I'm not sure if there's an API for that (buy orders). Regarding the less popular cards, I'll see if there's a possibility to optimize those listings but I think it won't be so easy as the information Valve provides is pretty basic.
