### ISSUE TITLE
Node.js module

### ISSUE THREAD

**Issue by Royalgamer06** [Nuklon/Steam-Economy-Enhancer#72]
I'm wondering what you think of the idea in turning this into a node.js module/script. Where it would automatically and periodically (configurable) use clean your steam inventory and organize your steam market listings according to your preferences. 
It would be like a personal bot, a bit like Archi's Steam Farm. It would be a great way to make everything fully automatic and save the user manual work from time to time. The user only has to watch how his steam wallet money grows.
If you want, I could help you with this.

**Comment by Nuklon** [comment]
I'm not really familiar with it, but if the current code can be kept mostly in tact with some minor changes then sure, feel free to submit a PR for it.
On Apr 4, 2018, at 20:23, Royalgamer06 <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm wondering what you think of the idea in turning this into a node.js module/script. Where it would automatically and periodically (configurable) use clean your steam inventory and organize your steam market listings according to your preferences.
It would be like a personal bot, a bit like Archi's Steam Farm. It would be a great way to make everything fully automatic and save the user manual work from time to time. The user only has to watch how his steam wallet money grows.
If you want, I could help you with this.

**Comment by Royalgamer06** [comment]
This module seems to cover much what your script does:
https://github.com/irqize/node-steam-market-sell
Might be interesting for you to take a look.
You may even end up forking it and improving it with parts of your script :)
