### ISSUE TITLE
Turn ancient market listing automatically into gems 

### ISSUE THREAD

**Issue by Royalgamer06** [Nuklon/Steam-Economy-Enhancer#73]
There are market items, that even if you put them on the market for the lowest price, will never sell. The only use for them then is to turn them into gems, and that is what I am proposing.

**Comment by Nuklon** [comment]
Yeah, this would be nice indeed, no time for this to code at the moment though, so I accept a PR for it.

**Comment by Nuklon** [comment]
Yes, that's the easiest solution right now :)

**Comment by woctezuma** [comment]
It is not always worth it to convert trading cards into gems: you may get as little as 1 gem for it, which is currently worth 1/50 of a cent. This automatic conversion would be a bit dangerous. People might prefer to trade their cards away.
