### ISSUE TITLE
g_rgAppContextData is not defined

### ISSUE THREAD

**Issue by Mokushiroku** [Nuklon/Steam-Economy-Enhancer#74]
Getting same error on both Chrome and Firefox.

ReferenceError: g_rgAppContextData is not defined
Stack trace:
userScript/<@user-script:https%3A//github.com/Nuklon/Steam%20Economy%20Enhancer:431:9
userScript@user-script:https%3A//github.com/Nuklon/Steam%20Economy%20Enhancer:385:2
scopeWrapper@user-script:https%3A//github.com/Nuklon/Steam%20Economy%20Enhancer:3821:9
@user-script:https%3A//github.com/Nuklon/Steam%20Economy%20Enhancer:361:17

**Comment by einsweniger** [comment]
Seems to be a problem with the way Greasemonkey does sandboxing.
Had the same error, works with tampermonkey

**Comment by Mokushiroku** [comment]
Thanks for that, I have now switched to tampermonkey.
