### ISSUE TITLE
Market issues

### ISSUE THREAD

**Issue by MakoSipper** [Nuklon/Steam-Economy-Enhancer#77]
Using it on the market page makes Steam deny me access to the whole steam community for about 10 minutes.

**Comment by zinnerzPT** [comment]
This has also been happening to me for a while now and makes it impossible to go through my listings as I have over 1000 items listed on the market.
A possible fix would be scanning the price of the items one by one and adding a delay in between them (just like how it does on the inventory price checks)

**Comment by Nuklon** [comment]
There's already a (significant) delay in loading market listings. You can try to increase this line:
https://github.com/Nuklon/Steam-Economy-Enhancer/blob/master/code.user.js#L2123

from 1000,1500 to say 5000,7500 and see if Steam still blocks you. I've about 500 listings here and I don't get blocked.

**Comment by Omicron666** [comment]
@zinnerzPT disable calculation of total amount from your market transactions in Enhanced Steam. It generates tons of requests on Steam Market page.

**Comment by MakoSipper** [comment]
@Omicron666 I did just that a few minutes ago, maybe that's what was causing the issue.

**Comment by zinnerzPT** [comment]
@Omicron666 that worked, thanks

**Comment by Nuklon** [comment]
Yes, enhanced steam can be problematic, you should disable it on market.
