### ISSUE TITLE
SUGGESTION: auto-sell items not at the lowest price 

### ISSUE THREAD

**Issue by pacopepepipo** [Nuklon/Steam-Economy-Enhancer#96]
Could be added an option to auto-sell inventory items but not straight at the minimum asked price but at for example 1 cent less than the lowest item offered?

Right now works like

lowest offered: 1
highst requested 0.1

And SEE will straight sell the item at 0.1, but it would be more useful to be able to put the item to sale at 0,99 and just wait instead of straight selling it.

And when I say 0.99, I mean a configurable margin, 0.01, 0.1, etc

Steam inventory helper have something like that, but fuck them and their spyware.

cheers!

ps: The "calculate prices as the lowest sell listing" that I think should work for what I ask, at least for me doesn't work at all.

**Comment by Nuklon** [comment]
That already exists as history :)

**Comment by pacopepepipo** [comment]
Hi

Can I ask how? As much as I try it, I can't see how to do it.
