### ISSUE TITLE
Doesn't work with Greasemonkey

### ISSUE THREAD

**Issue by leifmetcalf** [Nuklon/Steam-Economy-Enhancer#99]
With Violentmonkey the script works fine. With Greasemonkey, trying to sell any item gives the "… not added to market" error. Bulk-selling items hangs forever with the loading animation.

Maybe Greasemonkey should be removed as a possible requirement in the README?

**Comment by Nuklon** [comment]
Greasemoney removed, it works best with Violentmonkey.
